### ISSUE TITLE
Unable to add Github credentials due to new scope-prefix in access token:

### ISSUE THREAD

**Issue by marijnvermeulenadobe** [PMET-public/mdm#36]
I'm trying to add my Github credentials, as instructed, but I'm unable to add the newly created access token. Apparently, Github has added a scope prefix (containing an underscore) that is not accepted by the RegExp in the script: 

![Screenshot 2022-07-28 at 12 58 19](https://user-images.githubusercontent.com/28751167/181489865-52bc77b1-b74b-43b8-ad4b-f196dccf35e1.png)

`marijnvermeulen@Marijns-MacBook-Pro ~ % /var/folders/k3/93dmbtpj5lg9rqxpbx_8pm_80000gq/T/MDM-lite-create_auth_json.MSOERYW5 ; exit;

>> This script will prompt for your GitHub and Magento account information to create your /Users/marijnvermeulen/.composer/auth.json file. <<

If you prefer to create the file on your own, follow the instructions here:
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/dev_install.html#instgde-prereq-compose-clone-auth

GitHub Personal Access Token
1. Sign into GitHub https://github.com/
2. Go to your account Profile > Developer settings > Personal access tokens
3. Generate a new token with any name and 'repo' scope (no other selections are needed)
4. Paste the token here

Numbers [0-9] and letters [a-f] only (ex. 9662d057e4e52b1b236fa237a232349841e60b44e)> ghp_*******************************
Numbers [0-9] and letters [a-f] only (ex. 9662d057e4e52b1b236fa237a232349841e60b44e)>`

**Comment by marijnvermeulen-adobe** [comment]
Known issue, apparently my composer is outdated: https://support.magento.com/hc/en-us/articles/4402562382221-Github-token-issue-and-Composer-key-procedures

Interestingly though: I just started installing everything from scratch and I'm outdated OOTB ;)
